// Automatisch gegenereerd door sync-excel.ps1 - niet handmatig aanpassen
// Bronbestand: Database_routekaart_v3_elementaire leerdoelen en breuken uitgewerkt.xlsx
// Gegenereerd op: 2026-05-28 12:05

const CURRICULUM = {
  secties: [
    {
      id: 'B',
      naam: 'Breuken',
      kleur: '#E06C20',
      leerdoelen: [
        { id: 'B.0', naam: "Begrijpen wat een breuk is (tellend en noemer)", voorkennis: [] },
        { id: 'B.1', naam: "Enkelvoudige breuken vereenvoudigen", voorkennis: ['B.0'] },
        { id: 'B.2', naam: "Gemengde breuken vereenvoudigen", voorkennis: ['B.1'] },
        { id: 'B.3', naam: "Enkelvoudige breuken gelijknamig maken", voorkennis: ['B.1'] },
        { id: 'B.4', naam: "Gemengde breuken gelijknamig maken", voorkennis: ['B.2', 'B.3'] },
        { id: 'B.5', naam: "Enkelvoudige breuken optellen", voorkennis: ['B.3'] },
        { id: 'B.6', naam: "Gemengde breuken optellen", voorkennis: ['B.4', 'B.5'] },
        { id: 'B.7', naam: "Enkelvoudige breuken aftrekken", voorkennis: ['B.3'] },
        { id: 'B.8', naam: "Gemengde breuken aftrekken", voorkennis: ['B.6', 'B.7'] },
        { id: 'B.9', naam: "Enkelvoudige breuken vermenigvuldigen", voorkennis: ['B.1'] },
        { id: 'B.10', naam: "Gemengde breuken vermenigvuldigen", voorkennis: ['B.2', 'B.9'] },
        { id: 'B.11', naam: "Enkelvoudige breuken delen", voorkennis: ['B.9'] },
        { id: 'B.12', naam: "Gemengde breuken delen", voorkennis: ['B.10', 'B.11'] },
        { id: 'B.13', naam: "Breuk omrekenen naar percentage", voorkennis: ['B.1'] },
        { id: 'B.14', naam: "Percentage omrekenen naar breuk", voorkennis: ['B.1'] },
        { id: 'B.15', naam: "Breuk omrekenen naar decimaal getal", voorkennis: ['B.1'] },
        { id: 'B.16', naam: "Decimaal getal omrekenen naar breuk", voorkennis: ['B.15'] },
      ]
    },
    {
      id: 'P',
      naam: 'Procenten',
      kleur: '#8E44AD',
      leerdoelen: [
        { id: 'P.1', naam: "Deel van een geheel in procenten uitrekenen", voorkennis: ['B.13'] },
        { id: 'P.2', naam: "Percentage van een getal berekenen (x% van y)", voorkennis: ['P.1'] },
        { id: 'P.3', naam: "Procentuele toename berekenen", voorkennis: ['P.2'] },
        { id: 'P.4', naam: "Procentuele afname berekenen", voorkennis: ['P.2'] },
        { id: 'P.5', naam: "Percentage na opeenvolgende toe- of afnames berekenen", voorkennis: ['P.3', 'P.4'] },
        { id: 'P.6', naam: "Het origineel berekenen gegeven een percentage en uitkomst", voorkennis: ['P.2'] },
        { id: 'P.7', naam: "Procentuele verandering berekenen tussen twee getallen", voorkennis: ['P.3'] },
        { id: 'P.8', naam: "Percentage omrekenen naar decimaal getal", voorkennis: ['P.1'] },
        { id: 'P.9', naam: "Decimaal getal omrekenen naar percentage", voorkennis: ['P.8'] },
        { id: 'P.10', naam: "Verhouding omzetten naar percentage", voorkennis: ['P.1'] },
      ]
    },
    {
      id: 'V',
      naam: 'Verhoudingen en Getallen',
      kleur: '#2980B9',
      leerdoelen: [
        { id: 'V.1', naam: "Verhouding schrijven als a:b", voorkennis: [] },
        { id: 'V.2', naam: "Verhouding vereenvoudigen", voorkennis: ['V.1'] },
        { id: 'V.3', naam: "Verhoudingstabel opstellen", voorkennis: ['V.1'] },
        { id: 'V.4', naam: "Ontbrekende waarde in een verhoudingstabel berekenen", voorkennis: ['V.3'] },
        { id: 'V.5', naam: "Schaalprobleem oplossen met een verhouding", voorkennis: ['V.4'] },
        { id: 'V.6', naam: "Eenheid omrekenen binnen hetzelfde stelsel (bijv. km naar m)", voorkennis: [] },
        { id: 'V.7', naam: "Eenheid omrekenen tussen grootheden (bijv. snelheid: km/h)", voorkennis: ['V.6'] },
        { id: 'V.8', naam: "Samengestelde grootheid interpreteren en gebruiken (bijv. km/h, €/kg)", voorkennis: ['V.7'] },
        { id: 'V.9', naam: "Gehele getallen optellen en aftrekken", voorkennis: [] },
        { id: 'V.10', naam: "Gehele getallen vermenigvuldigen en delen", voorkennis: ['V.9'] },
        { id: 'V.11', naam: "Decimale getallen optellen en aftrekken", voorkennis: ['V.9'] },
        { id: 'V.12', naam: "Decimale getallen vermenigvuldigen en delen", voorkennis: ['V.10', 'V.11'] },
        { id: 'V.13', naam: "Eigenschappen van gehele getallen benoemen (deelbaar, priemgetal, kwadraat)", voorkennis: [] },
        { id: 'V.14', naam: "Machtsverheffing uitvoeren (gehele machten)", voorkennis: ['V.10'] },
        { id: 'V.15', naam: "Vierkantswortel van een getal bepalen", voorkennis: ['V.14'] },
        { id: 'V.16', naam: "Negatieve getallen plaatsen op een getallenlijn", voorkennis: [] },
        { id: 'V.17', naam: "Rekenen met negatieve gehele getallen", voorkennis: ['V.16'] },
        { id: 'V.18', naam: "Machten van 10 schrijven en gebruiken", voorkennis: ['V.14'] },
      ]
    },
    {
      id: 'A',
      naam: 'Algebra en Verbanden',
      kleur: '#27AE60',
      leerdoelen: [
        { id: 'A.1', naam: "Patroon in een rij getallen herkennen", voorkennis: [] },
        { id: 'A.2', naam: "Een patroon in een rij getallen beschrijven in woorden", voorkennis: ['A.1'] },
        { id: 'A.3', naam: "Een rij getallen voortzetten op basis van een patroon", voorkennis: ['A.2'] },
        { id: 'A.4', naam: "Patroon in een reeks figuren herkennen en beschrijven", voorkennis: [] },
        { id: 'A.5', naam: "Een reeks figuren voortzetten op basis van een patroon", voorkennis: ['A.4'] },
        { id: 'A.6', naam: "Variabele als onbekende herkennen en gebruiken", voorkennis: [] },
        { id: 'A.7', naam: "Formule opstellen bij een situatie of tabel", voorkennis: ['A.6'] },
        { id: 'A.8', naam: "Waarden berekenen met een gegeven formule", voorkennis: ['A.7'] },
        { id: 'A.9', naam: "Invoerwaarden zoeken bij een gewenste uitvoerwaarde", voorkennis: ['A.8'] },
        { id: 'A.10', naam: "Tabel maken bij een formule", voorkennis: ['A.7'] },
        { id: 'A.11', naam: "Grafiek maken bij een tabel of formule", voorkennis: ['A.10'] },
        { id: 'A.12', naam: "Aflezen van een grafiek (uitvoerwaarde bij gegeven invoerwaarde)", voorkennis: ['A.11'] },
        { id: 'A.13', naam: "Lineair verband herkennen in tabel, grafiek en formule", voorkennis: ['A.11'] },
        { id: 'A.14', naam: "Richtingscoëfficiënt en beginwaarde van een lineair verband bepalen", voorkennis: ['A.13'] },
        { id: 'A.15', naam: "Beschrijving, tabel, grafiek en formule van een verband in elkaar omzetten", voorkennis: ['A.13'] },
        { id: 'A.16', naam: "Verbanden tussen grootheden identificeren en beschrijven", voorkennis: ['A.13'] },
        { id: 'A.17', naam: "Vergelijking opstellen bij een situatie", voorkennis: ['A.7'] },
        { id: 'A.18', naam: "Lineaire vergelijking oplossen (één onbekende)", voorkennis: ['A.17'] },
        { id: 'A.19', naam: "Oplossing van een vergelijking interpreteren in de context", voorkennis: ['A.18'] },
        { id: 'A.20', naam: "Grafische oplossing van een vergelijking aflezen", voorkennis: ['A.12', 'A.18'] },
      ]
    },
    {
      id: 'M',
      naam: 'Meetkunde',
      kleur: '#C0392B',
      leerdoelen: [
        { id: 'M.1', naam: "Eigenschappen van basisvormen benoemen (vierkant, rechthoek, driehoek, cirkel)", voorkennis: [] },
        { id: 'M.2', naam: "Eigenschappen van ruimtelijke figuren benoemen (balk, kubus, cilinder)", voorkennis: [] },
        { id: 'M.3', naam: "Omtrek van een rechthoek berekenen", voorkennis: ['M.1'] },
        { id: 'M.4', naam: "Omtrek van een driehoek berekenen", voorkennis: ['M.1'] },
        { id: 'M.5', naam: "Omtrek van een samengestelde vlakke figuur berekenen", voorkennis: ['M.3', 'M.4'] },
        { id: 'M.6', naam: "Oppervlakte van een rechthoek berekenen", voorkennis: ['M.1'] },
        { id: 'M.7', naam: "Oppervlakte van een driehoek berekenen", voorkennis: ['M.6'] },
        { id: 'M.8', naam: "Oppervlakte van een samengestelde vlakke figuur berekenen", voorkennis: ['M.6', 'M.7'] },
        { id: 'M.9', naam: "Omtrek en oppervlakte van een cirkel berekenen", voorkennis: ['M.1'] },
        { id: 'M.10', naam: "Inhoud van een rechthoekige balk berekenen", voorkennis: ['M.6'] },
        { id: 'M.11', naam: "Inhoud van een cilinder berekenen", voorkennis: ['M.9', 'M.10'] },
        { id: 'M.12', naam: "Bovenaanzicht, zijaanzicht en vooraanzicht van een ruimtelijk figuur tekenen", voorkennis: ['M.2'] },
        { id: 'M.13', naam: "Ruimtelijk figuur herkennen vanuit een 2D-representatie", voorkennis: ['M.12'] },
        { id: 'M.14', naam: "Kijklijnen gebruiken bij perspectief en zichtbaarheid", voorkennis: ['M.13'] },
        { id: 'M.15', naam: "Figuur verschuiven (translatie)", voorkennis: ['M.1'] },
        { id: 'M.16', naam: "Figuur spiegelen (reflectie)", voorkennis: ['M.1'] },
        { id: 'M.17', naam: "Figuur draaien (rotatie)", voorkennis: ['M.1'] },
        { id: 'M.18', naam: "Figuur vergroten of verkleinen met een schaalfactor", voorkennis: ['M.1'] },
      ]
    },
    {
      id: 'S',
      naam: 'Statistiek',
      kleur: '#16A085',
      leerdoelen: [
        { id: 'S.1', naam: "Gegevens ordenen in een frequentietabel", voorkennis: [] },
        { id: 'S.2', naam: "Staafdiagram maken bij gegeven data", voorkennis: ['S.1'] },
        { id: 'S.3', naam: "Cirkeldiagram maken bij gegeven data", voorkennis: ['S.1'] },
        { id: 'S.4', naam: "Lijndiagram maken bij gegeven data", voorkennis: ['S.1'] },
        { id: 'S.5', naam: "Histogram maken bij gegeven data", voorkennis: ['S.1'] },
        { id: 'S.6', naam: "Infographic interpreteren", voorkennis: ['S.2'] },
        { id: 'S.7', naam: "Staafdiagram interpreteren en conclusies trekken", voorkennis: ['S.2'] },
        { id: 'S.8', naam: "Cirkeldiagram interpreteren en conclusies trekken", voorkennis: ['S.3'] },
        { id: 'S.9', naam: "Lijndiagram interpreteren en conclusies trekken", voorkennis: ['S.4'] },
        { id: 'S.10', naam: "Gemiddelde berekenen", voorkennis: ['S.1'] },
        { id: 'S.11', naam: "Mediaan bepalen", voorkennis: ['S.1'] },
        { id: 'S.12', naam: "Modus bepalen", voorkennis: ['S.1'] },
        { id: 'S.13', naam: "Spreidingsbreedte berekenen", voorkennis: ['S.10'] },
        { id: 'S.14', naam: "Gemiddelde, mediaan of modus beredeneerd kiezen als maat voor het centrum", voorkennis: ['S.10', 'S.11', 'S.12'] },
        { id: 'S.15', naam: "Representatievorm beredeneerd kiezen bij een dataset", voorkennis: ['S.2', 'S.3', 'S.4'] },
        { id: 'S.16', naam: "Conclusies bij een grafische representatie beoordelen op juistheid", voorkennis: ['S.7', 'S.8', 'S.9'] },
        { id: 'S.17', naam: "Patronen en verbanden herkennen in een dataset", voorkennis: ['S.7'] },
      ]
    },
    {
      id: 'K',
      naam: 'Kansen en Tellen',
      kleur: '#D4A017',
      leerdoelen: [
        { id: 'K.1', naam: "Kans als breuk schrijven (gunstig/totaal)", voorkennis: [] },
        { id: 'K.2', naam: "Kans als verhouding schrijven", voorkennis: ['K.1'] },
        { id: 'K.3', naam: "Kans als percentage uitdrukken", voorkennis: ['K.1', 'P.1'] },
        { id: 'K.4', naam: "Kans als decimaal getal uitdrukken", voorkennis: ['K.1', 'B.15'] },
        { id: 'K.5', naam: "Kans inschatten op basis van een gegeven kanswaarde", voorkennis: ['K.1'] },
        { id: 'K.6', naam: "Complementaire kans berekenen", voorkennis: ['K.1'] },
        { id: 'K.7', naam: "Empirische kans bepalen op basis van data", voorkennis: ['K.1', 'S.1'] },
        { id: 'K.8', naam: "Verschil tussen theoretische en empirische kans uitleggen", voorkennis: ['K.1', 'K.7'] },
        { id: 'K.9', naam: "Verwachtingswaarde berekenen", voorkennis: ['K.1', 'V.12'] },
        { id: 'T.1', naam: "Wegendiagram opstellen en gebruiken", voorkennis: [] },
        { id: 'T.2', naam: "Boomdiagram opstellen en gebruiken", voorkennis: ['T.1'] },
        { id: 'T.3', naam: "Rijtjesregel (multiplicatieregel) toepassen", voorkennis: ['T.1'] },
        { id: 'K.10', naam: "Kansen bij samengestelde gebeurtenis berekenen met boomdiagram", voorkennis: ['K.1', 'T.2'] },
      ]
    },
    {
      id: 'D',
      naam: 'Wiskundige Werkwijzen',
      kleur: '#2C3E50',
      leerdoelen: [
        { id: 'D.1', naam: "Wiskundevraagstuk door elkaar oefenen (gemengde opgaven)", voorkennis: [] },
        { id: 'D.2', naam: "Wiskundige uitkomst omzetten naar een betekenisvolle oplossing in context", voorkennis: [] },
        { id: 'D.3', naam: "Situatie of probleem analyseren en een aanpak kiezen", voorkennis: [] },
        { id: 'D.4', naam: "Een niet-routinematig probleem zelfstandig aanpakken en uitvoeren", voorkennis: ['D.3'] },
        { id: 'D.5', naam: "Heuristieken toepassen (bijv. tekening maken, speciaal geval, terug redeneren)", voorkennis: ['D.3'] },
        { id: 'D.6', naam: "Aanpak, uitvoering en oplossing evalueren en bijstellen", voorkennis: ['D.4'] },
        { id: 'D.7', naam: "Situatie weergeven als wiskundig model (schema, vergelijking, grafiek)", voorkennis: [] },
        { id: 'D.8', naam: "Relevante kenmerken selecteren en niet-relevante weglaten bij modelleren", voorkennis: ['D.7'] },
        { id: 'D.9', naam: "Geschikt model kiezen voor een situatie en die keuze beargumenteren", voorkennis: ['D.7', 'D.8'] },
        { id: 'D.10', naam: "Abstract model gebruiken om een aanpak of situatie te interpreteren", voorkennis: ['D.9'] },
        { id: 'D.11', naam: "Vermoeden of bewering formuleren", voorkennis: [] },
        { id: 'D.12', naam: "Logische redenering opstellen om een bewering te onderbouwen", voorkennis: ['D.11'] },
        { id: 'D.13', naam: "Redenering van een ander kritisch evalueren", voorkennis: ['D.12'] },
        { id: 'D.14', naam: "Algoritme met een beperkt aantal stappen beschrijven", voorkennis: [] },
        { id: 'D.15', naam: "Uitleggen hoe een algoritme tot een vast resultaat leidt", voorkennis: ['D.14'] },
        { id: 'D.16', naam: "Resultaat van een doorlopen algoritme beoordelen", voorkennis: ['D.15'] },
        { id: 'D.17', naam: "Algoritme ontwerpen voor de aanpak van een probleem", voorkennis: ['D.14'] },
        { id: 'D.18', naam: "Mogelijkheden en beperkingen van een algoritme beschrijven", voorkennis: ['D.15'] },
        { id: 'D.19', naam: "Wiskundig probleem in uitdagende (challenge-)vorm aanpakken", voorkennis: [] },
      ]
    },
    {
      id: 'G',
      naam: 'Wiskundetaal en Gereedschap',
      kleur: '#6C3483',
      leerdoelen: [
        { id: 'G.1', naam: "Wiskundige symbolen en notaties correct gebruiken", voorkennis: [] },
        { id: 'G.2', naam: "Berekeningen en aanpakken leesbaar weergeven", voorkennis: ['G.1'] },
        { id: 'G.3', naam: "Representatievorm kiezen om een redenering inzichtelijk te maken", voorkennis: ['G.1'] },
        { id: 'G.4', naam: "Representatievorm kritisch beoordelen op geschiktheid", voorkennis: ['G.3'] },
        { id: 'G.5', naam: "Relaties leggen tussen verschillende representaties van hetzelfde concept", voorkennis: ['G.3'] },
        { id: 'G.6', naam: "Meetinstrument beredeneerd kiezen op basis van mogelijkheden en nauwkeurigheid", voorkennis: [] },
        { id: 'G.7', naam: "Meetresultaat of uitkomst van tevoren schatten", voorkennis: [] },
        { id: 'G.8', naam: "Meetinstrument correct gebruiken en bijbehorende wiskundetaal hanteren", voorkennis: ['G.6'] },
        { id: 'G.9', naam: "Meetresultaat bepalen, interpreteren en beoordelen", voorkennis: ['G.8'] },
        { id: 'G.10', naam: "Berekening uitvoeren met een digitaal instrument en nauwkeurigheid aangeven", voorkennis: ['G.8'] },
      ]
    },
  ],

  activiteiten: [
    { id: 'act_001', leerdoelen: ['B.3'], naam: "Oefenen", bron: "Algebra Kit", url: 'https://practice.algebrakit.com/nl/practice', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: true },
    { id: 'act_002', leerdoelen: ['B.4'], naam: "Oefenen", bron: "Algebra Kit", url: 'https://practice.algebrakit.com/nl/practice', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: true },
    { id: 'act_003', leerdoelen: ['B.5'], naam: "Oefenen", bron: "Algebra Kit", url: 'https://practice.algebrakit.com/nl/practice', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: true },
    { id: 'act_004', leerdoelen: ['B.6'], naam: "Oefenen", bron: "Algebra Kit", url: 'https://practice.algebrakit.com/nl/practice', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: true },
    { id: 'act_005', leerdoelen: ['B.7'], naam: "Oefenen", bron: "Algebra Kit", url: 'https://practice.algebrakit.com/nl/practice', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: true },
    { id: 'act_006', leerdoelen: ['B.8'], naam: "Oefenen", bron: "Algebra Kit", url: 'https://practice.algebrakit.com/nl/practice', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: true },
    { id: 'act_007', leerdoelen: ['B.9'], naam: "Oefenen", bron: "Algebra Kit", url: 'https://practice.algebrakit.com/nl/practice', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: true },
    { id: 'act_008', leerdoelen: ['B.10'], naam: "Oefenen", bron: "Algebra Kit", url: 'https://practice.algebrakit.com/nl/practice', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: true },
    { id: 'act_009', leerdoelen: ['B.3', 'B.5', 'B.7', 'B.9', 'P.2'], naam: "Oefenen", bron: "Algebra Kit", url: 'https://practice.algebrakit.com/nl/practice', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: true },
    { id: 'act_010', leerdoelen: ['B.4', 'B.6', 'B.8', 'B.10', 'P.2'], naam: "Oefenen", bron: "Algebra Kit", url: 'https://practice.algebrakit.com/nl/practice', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: true },
    { id: 'act_011', leerdoelen: [], naam: "Wageningse methode 7.1 Breuken intro", bron: "Wageningse methode", url: 'https://www.wageningse-methode.nl/content/lj1-hv-h07/lj1-hv-h07-01/lj1-hv-h07-01.html', niveau: 'havo/vwo', soort: 'Oriënteren', inloggen: false, bijzonderheden: "Er komen variabelen in de breuken voor" },
    { id: 'act_012', leerdoelen: [], naam: "Wageningse methode 7.2 Breuken Wat is een breuk?", bron: "Wageningse methode", url: 'https://www.wageningse-methode.nl/content/lj1-hv-h07/lj1-hv-h07-02/lj1-hv-h07-02.html', niveau: 'havo/vwo', soort: 'Holistisch', inloggen: false, bijzonderheden: "Er komen variabelen in de breuken voor" },
    { id: 'act_013', leerdoelen: ['B.11', 'B.12'], naam: "Wageningse methode 7.3 Breuken Breuken en procenten", bron: "Wageningse methode", url: 'https://www.wageningse-methode.nl/content/lj1-hv-h07/lj1-hv-h07-03/lj1-hv-h07-03.html', niveau: 'havo/vwo', soort: 'Holistisch', inloggen: false, bijzonderheden: "Er komen variabelen in de breuken voor" },
    { id: 'act_014', leerdoelen: ['B.3', 'B.5'], naam: "Wageningse methode 7.4 Breuken Breuken optellen en aftrekken", bron: "Wageningse methode", url: 'https://www.wageningse-methode.nl/content/lj1-hv-h07/lj1-hv-h07-04/lj1-hv-h07-04.html', niveau: 'havo/vwo', soort: 'Holistisch', inloggen: false },
    { id: 'act_015', leerdoelen: ['B.8'], naam: "Wageningse methode 7.5 Breuken Deel van een geheel", bron: "Wageningse methode", url: 'https://www.wageningse-methode.nl/content/lj1-hv-h07/lj1-hv-h07-05/lj1-hv-h07-05.html', niveau: 'havo/vwo', soort: 'Holistisch', inloggen: false },
    { id: 'act_016', leerdoelen: ['B.9'], naam: "Wageningse methode 7.6 Breuken Delen door een breuk", bron: "Wageningse methode", url: 'https://www.wageningse-methode.nl/content/lj1-hv-h07/lj1-hv-h07-06/lj1-hv-h07-06.html', niveau: 'havo/vwo', soort: 'Holistisch', inloggen: false },
    { id: 'act_017', leerdoelen: ['B.11', 'B.12'], naam: "Wageningse methode 7.7 Breuken Eindpunt", bron: "Wageningse methode", url: 'https://www.wageningse-methode.nl/content/lj1-hv-h07/lj1-hv-h07-07/lj1-hv-h07-07.html', niveau: 'havo/vwo', soort: 'Samenvatting', inloggen: false },
    { id: 'act_018', leerdoelen: ['B.0'], naam: "Breuken.nl: Wat is een breuk? (uitleg teller, noemer, breukstreep)", bron: "Breuken.nl", url: 'https://www.breuken.nl/wat-is-een-breuk/', niveau: 'vmbo-t/havo/vwo', soort: 'uitleg', inloggen: false },
    { id: 'act_019', leerdoelen: ['B.1'], naam: "Breuken.nl: Breuken vereenvoudigen — uitleg en oefeningen", bron: "Breuken.nl", url: 'https://www.breuken.nl/vereenvoudigen/', niveau: 'vmbo-t/havo/vwo', soort: 'uitleg/verwerken', inloggen: false },
    { id: 'act_020', leerdoelen: ['B.1'], naam: "Breuken.nl: 5-stappenplan vereenvoudigen niveau 1", bron: "Breuken.nl", url: 'https://www.breuken.nl/breuken-vereenvoudigen-niveau-1/', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: false },
    { id: 'act_021', leerdoelen: ['B.2'], naam: "Breuken.nl: 5-stappenplan vereenvoudigen niveau 2 (gemengde breuken)", bron: "Breuken.nl", url: 'https://www.breuken.nl/breuken-vereenvoudigen-niveau-2/', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: false },
    { id: 'act_022', leerdoelen: ['B.3'], naam: "Breuken.nl: Gelijknamig maken — uitleg en oefeningen", bron: "Breuken.nl", url: 'https://www.breuken.nl/gelijknamig-maken/', niveau: 'vmbo-t/havo/vwo', soort: 'uitleg/verwerken', inloggen: false },
    { id: 'act_023', leerdoelen: ['B.3', 'B.4'], naam: "Breuken.nl: 5-stappenplan gelijknamig maken", bron: "Breuken.nl", url: 'https://www.breuken.nl/breuken-gelijknamig-maken/', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: false },
    { id: 'act_024', leerdoelen: ['B.5'], naam: "Breuken.nl: Breuken optellen — uitleg en oefeningen (enkelvoudig en gemengd)", bron: "Breuken.nl", url: 'https://www.breuken.nl/optellen/', niveau: 'vmbo-t/havo/vwo', soort: 'uitleg/verwerken', inloggen: false },
    { id: 'act_025', leerdoelen: ['B.5'], naam: "Breuken.nl: 5-stappenplan optellen niveau 1 (gelijknamige breuken)", bron: "Breuken.nl", url: 'https://www.breuken.nl/breuken-optellen-niveau-1/', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: false },
    { id: 'act_026', leerdoelen: ['B.5'], naam: "Breuken.nl: 5-stappenplan optellen niveau 2 (ongelijknamige breuken)", bron: "Breuken.nl", url: 'https://www.breuken.nl/breuken-optellen-niveau-2/', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: false },
    { id: 'act_027', leerdoelen: ['B.6'], naam: "Breuken.nl: 5-stappenplan optellen niveau 3 (gemengde breuken)", bron: "Breuken.nl", url: 'https://www.breuken.nl/breuken-optellen-niveau-3/', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: false },
    { id: 'act_028', leerdoelen: ['B.7'], naam: "Breuken.nl: Breuken aftrekken — uitleg en oefeningen", bron: "Breuken.nl", url: 'https://www.breuken.nl/aftrekken/', niveau: 'vmbo-t/havo/vwo', soort: 'uitleg/verwerken', inloggen: false },
    { id: 'act_029', leerdoelen: ['B.7'], naam: "Breuken.nl: 5-stappenplan aftrekken niveau 1 (gelijknamige breuken)", bron: "Breuken.nl", url: 'https://www.breuken.nl/breuken-aftrekken-niveau-1/', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: false },
    { id: 'act_030', leerdoelen: ['B.7'], naam: "Breuken.nl: 5-stappenplan aftrekken niveau 2 (ongelijknamige breuken)", bron: "Breuken.nl", url: 'https://www.breuken.nl/breuken-aftrekken-niveau-2/', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: false },
    { id: 'act_031', leerdoelen: ['B.8'], naam: "Breuken.nl: 5-stappenplan aftrekken niveau 3 (gemengde breuken)", bron: "Breuken.nl", url: 'https://www.breuken.nl/breuken-aftrekken-niveau-3/', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: false },
    { id: 'act_032', leerdoelen: ['B.9'], naam: "Breuken.nl: Breuken vermenigvuldigen — uitleg en oefeningen", bron: "Breuken.nl", url: 'https://www.breuken.nl/vermenigvuldigen/', niveau: 'vmbo-t/havo/vwo', soort: 'uitleg/verwerken', inloggen: false },
    { id: 'act_033', leerdoelen: ['B.9'], naam: "Breuken.nl: 5-stappenplan vermenigvuldigen niveau 1", bron: "Breuken.nl", url: 'https://www.breuken.nl/breuken-vermenigvuldigen-niveau-1/', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: false },
    { id: 'act_034', leerdoelen: ['B.11'], naam: "Breuken.nl: Breuken delen — uitleg en oefeningen", bron: "Breuken.nl", url: 'https://www.breuken.nl/delen/', niveau: 'vmbo-t/havo/vwo', soort: 'uitleg/verwerken', inloggen: false },
    { id: 'act_035', leerdoelen: ['B.11'], naam: "Breuken.nl: 5-stappenplan delen niveau 1", bron: "Breuken.nl", url: 'https://www.breuken.nl/breuken-delen-1/', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: false },
    { id: 'act_036', leerdoelen: ['B.13'], naam: "Breuken.nl: Van breuken naar procenten — uitleg en oefeningen", bron: "Breuken.nl", url: 'https://www.breuken.nl/procenten/', niveau: 'vmbo-t/havo/vwo', soort: 'uitleg/verwerken', inloggen: false },
    { id: 'act_037', leerdoelen: ['B.15'], naam: "Khan Academy: Breuken omschrijven naar decimale getallen (oefenen)", bron: "Khan Academy", url: 'https://nl.khanacademy.org/math/arithmetic/arith-decimals/arith-review-decimals-to-fractions/e/converting_fractions_to_decimals', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: false },
    { id: 'act_038', leerdoelen: ['B.16'], naam: "Khan Academy: Decimale getallen omschrijven tot breuken (oefenen)", bron: "Khan Academy", url: 'https://nl.khanacademy.org/math/arithmetic/arith-decimals/arith-review-decimals-to-fractions/e/converting_decimals_to_fractions_1', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: false },
    { id: 'act_039', leerdoelen: ['B.1', 'B.3', 'B.5', 'B.7', 'B.9', 'B.11'], naam: "Breuken.nl: Breuken Duiken — oefenspel (kies zelf het onderwerp)", bron: "Breuken.nl", url: 'https://www.breuken.nl/breuken-duiken.html', niveau: 'vmbo-t/havo/vwo', soort: 'verwerken', inloggen: false, bijzonderheden: "Leerling kiest zelf welke breukbewerking wordt geoefend" },
    { id: 'act_040', leerdoelen: ['B.0', 'B.1', 'B.2', 'B.3', 'B.5', 'B.7', 'B.9', 'B.11', 'B.13', 'B.15'], naam: "Wikiwijs: Uitleg en oefenen met breuken, procenten en kommagetallen (volledig arrangement)", bron: "Wikiwijs", url: 'https://maken.wikiwijs.nl/57988/Uitleg_en_Oefenen_met_breuken__en_procenten_en_kommagetallen_', niveau: 'vmbo-t/havo/vwo', soort: 'holistisch', inloggen: false, bijzonderheden: "Combineert uitleg, oefensites en werkbladen; behandelt ook relatie breuk-decimaal-procent" },
  ]
};
